# Generated by Django 5.1.2 on 2024-10-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('AccountNumber', models.IntegerField(primary_key='AccountNumber', serialize=False)),
                ('IFSCcode', models.IntegerField()),
                ('LoanAmount', models.FloatField()),
            ],
        ),
    ]
