# Generated by Django 5.1.2 on 2024-10-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='AccountNumber',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='IFSCcode',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='loan',
            name='LoanAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
