# Generated by Django 5.1.2 on 2024-10-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0002_alter_loan_accountnumber_alter_loan_ifsccode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='Email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
    ]
